---
git:
  requireCleanWorkingDir: false
  requireUpstream: true
  requireBranch: master
  commit: false
  commitMessage: Release ${version}
  tag: true
  tagName: v${version}
  tagAnnotation: Release ${version}
  pushArgs:
  - "--follow-tags"
github:
  release: true
  releaseName: Release ${version}
  preRelease: false
  draft: true
  assets:
  - styles-vale/*.zip
npm:
  publish: false
hooks:
  "after:bump": bin\build-release.bat
# Linux version:
#  "after:bump": bin/build-release.sh
